const Images : { [key: string]: any }= {
    image1: require('./DrinksImg/cubaLibre.png'),
    image2: require('./DrinksImg/whiteRussian.png'),
    image3: require('./DrinksImg/blackRussian.png'),
    image4: require('./DrinksImg/mojito.png'),
    image5: require('./DrinksImg/cosmopolitan.png'),
    image6: require('./DrinksImg/negroni.png'),
    image7: require('./DrinksImg/sexOnTheBeach.png'),
    image8: require('./DrinksImg/aperolSpritz.png'),
    image9: require('./DrinksImg/tomCollins.png'),
    image10: require('./DrinksImg/moscowMule.png'),
    image11: require('./DrinksImg/jagerbomb.png'),
    image12: require('./DrinksImg/tequilaSunrise.png'),
    image13: require('./DrinksImg/longIslandIcedTea.png'),
    image14: require('./DrinksImg/krwawaMary.png'),
    image15: require('./DrinksImg/martini.png'),
    image16: require('./DrinksImg/pornstarMartini.png'),
    image17: require('./DrinksImg/oldFashioned.png'),
    image18: require('./DrinksImg/whiskySour.png'),
    image19: require('./DrinksImg/margarita.png'),
    image20: require('./DrinksImg/caipirinia.png'),
    image21: require('./DrinksImg/vesperMartin.png'),
    image22: require('./DrinksImg/manhattan.png'),
    image23: require('./DrinksImg/daiquiri.png'),
    image24: require('./DrinksImg/basilSmash.png'),
    image25: require('./DrinksImg/darkNstormy.png'),
    image26: require('./DrinksImg/zombie.png'),
    image27: require('./DrinksImg/amarettoSour.png'),
    image28: require('./DrinksImg/cloverClub.png'),
    image29: require('./DrinksImg/americano.png'),
    image30: require('./DrinksImg/maiTai.png'),
    image31: require('./DrinksImg/paloma.png'),
    image32: require('./DrinksImg/penicylina.png'),
    image33: require('./DrinksImg/dryMartini.png'),
    image34: require('./DrinksImg/espressoMartini.png'),
    image35: require('./DrinksImg/french75.png'),
    image36: require('./DrinksImg/pinaColada.png'),
    image37: require('./DrinksImg/dirtyMartini.png')
};

export default Images;