const Images : { [key: string]: any }= {
    image1: require('../DrinksImg/CubaLibre.png'),
    image2: require('../DrinksImg/WhiteRussian.png'),
    image3: require('../DrinksImg/BlackRussian.png'),
    image4: require('../DrinksImg/Mojito.png'),
    image5: require('../DrinksImg/Cosmopolitan.png'),
    image6: require('../DrinksImg/Negroni.png'),
    image7: require('../DrinksImg/SexOnTheBeach.png'),
    image8: require('../DrinksImg/AperolSpritz.png'),
    image9: require('../DrinksImg/TomCollins.png'),
    image10: require('../DrinksImg/MoscowMule.png'),
    image11: require('../DrinksImg/Jagerbomb.png'),
    image12: require('../DrinksImg/TequilaSunrise.png'),
    image13: require('../DrinksImg/LongIslandIcedTea.png'),
    image14: require('../DrinksImg/KrwawaMary.png'),
    image15: require('../DrinksImg/Martini.png'),
    image16: require('../DrinksImg/PornstarMartini.png'),
    image17: require('../DrinksImg/OldFashioned.png'),
    image18: require('../DrinksImg/WhiskySour.png'),
    image19: require('../DrinksImg/Margarita.png'),
    image20: require('../DrinksImg/Caipirinia.png'),
    image21: require('../DrinksImg/VesperMartin.png'),
    image22: require('../DrinksImg/Manhattan.png'),
    image23: require('../DrinksImg/Daiquiri.png'),
    image24: require('../DrinksImg/BasilSmash.png'),
    image25: require('../DrinksImg/DarkNstormy.png'),
    image26: require('../DrinksImg/Zombie.png'),
    image27: require('../DrinksImg/AmarettoSour.png'),
    image28: require('../DrinksImg/CloverClub.png'),
    image29: require('../DrinksImg/Americano.png'),
    image30: require('../DrinksImg/MaiTai.png'),
    image31: require('../DrinksImg/Paloma.png'),
    image32: require('../DrinksImg/Penicylina.png'),
    image33: require('../DrinksImg/DryMartini.png'),
    image34: require('../DrinksImg/EspressoMartini.png'),
    image35: require('../DrinksImg/French75.png'),
    image36: require('../DrinksImg/PinaColada.png'),
    image37: require('../DrinksImg/PDirtyMartini.png')
};

export default Images;